version: 2

references:
  workspace_root: &workspace_root
    /home/circleci/prospector
  cache_key: &cache_key
    dependencies-{{ .Environment.CIRCLE_SHA1 }}
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  restore_cache: &restore_cache
    restore_cache:
      key: *cache_key
  save_cache: &save_cache
    save_cache:
      key: *cache_key
      paths:
        - .

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: rsrichardstevens/circleci-node-aws:latest-browsers

jobs:
  build:
    <<: *defaults
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore dependencies from cache
      - *restore_cache
      # Install project dependencies
      - run:
          name: Installing
          command: npm install
      - *save_cache
  lint:
    <<: *defaults
    steps:
      # Checkout the code from the branch into the working_directory
      - *attach_workspace
      # Restore dependencies from cache
      - *restore_cache
      - run:
          name: Linting
          command: npm run lint
      - *save_cache
  runner:
    <<: *defaults
    steps:
      # Checkout the code from the branch into the working_directory
      - *attach_workspace
      # Restore dependencies from cache
      - *restore_cache
      - run:
          name: Start Runner
          command: npm run start
      - *save_cache
workflows:
  version: 2
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
      - runner:
          requires:
            - build
          filters:
            branches:
              only: master
